### ISSUE TITLE
Filter by Roles

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#10]
Ability to filter roles - hence include or excluding them as a global setting. Like I want to be able to only show the metadata for the VFX role.

**Comment by latenitefilms** [comment]
@samplue - How would you actually see this working? Would we add a new textbox for "Filter" where you'd type in the role name?

**Comment by samplue** [comment]
@latenitefilms Maybe similar to Fast Collections. When you drag the project on the Generator, it will present you with a list of all Video roles where you can then select/deselect them?! 

![Sam_2024-01-03_14h11m03](https://github.com/latenitefilms/Metaburner/assets/78317416/915d7531-22c8-4ef5-92be-93ab8861ee36)

**Comment by latenitefilms** [comment]
Ummm... this is possible, but introduces a lot of complexity. For example, what happens if you drag a FCPXML, then drag another one which has different roles? I'd also need to build my own UI for this in the Inspector. It's possible we could just add a "Filter" button to the "Controls" which then pops up a window to do this?

I'll have a think and a play.

What's the use case? Do you want to apply the Title over the whole timeline, but only for the data to appear over certain types of clips?

**Comment by samplue** [comment]
Yes, maybe it's easier to add a "Filter" button as you suggested.

_"Do you want to apply the Title over the whole timeline, but only for the data to appear over certain types of clips?"_
Exactly, for certain exports I'd only want to show metadata for VFX or transformed clips. Much easier and faster to place the generator over the entire timeline.

**Comment by latenitefilms** [comment]
Will see what I can come up with. This will probably be one of the last things on the to-do list though, as it's pretty niche, and would require a whole new UI.

**Comment by latenitefilms** [comment]
This will be added in the next beta.
