### ISSUE TITLE
Complex timelines will drop frames

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#47]
On complex timelines (>30mins) frames will be dropped during playback when the Metaburner title is applied. Should I also file this feedback to Apple?!

**Comment by latenitefilms** [comment]
Are there any errors in the log files?

Metaburner now caches all the processed data and only loads the FCPXML data if you have a Lua text layer enabled, so after the first frame, the plugin should just be reading from its own memory, so there shouldn't be any issue reading the data.

What happens if you disable everything EXCEPT the Metaburner title? Does it still drop frames?

**Comment by samplue** [comment]
Will test tomorrow and report back!

**Comment by samplue** [comment]
I did a couple of tests and enabled the "Stop playback when frames are dropped" warning:

1. disable all roles except the metaburner title - will drop frames and FCP will throw out the warning message
2. disable all clips in the timeline except the metaburner title - will drop frames...
3. disable the Metaburner title - no frames will be dropped

There were no crash logs in the DiagnosticsReport folder.

[Metaburner Renderer - 1.0.4 (32).log.zip](https://github.com/latenitefilms/Metaburner/files/13997654/Metaburner.Renderer.-.1.0.4.32.log.zip)

**Comment by latenitefilms** [comment]
There doesn't seem to be any errors in that log file related to rendering.

Even though we're caching the processed data and the FCPXML data on the FxPlug side, maybe internally Final Cut Pro is still trying to read all the data, even if it's not using it.

One thing we can try is to disable saving the FCPXML data to the Effect.

Just to confirm though... everything works fine and plays back fine with smaller timelines, it's just these larger ones that fail?

What happens if you take this complex timeline, duplicate it, and delete all the audio? Does it still drop frames?

**Comment by samplue** [comment]
Yes, smaller/shorter timelines work fine without dropping frames.

Duplicating, detaching audio and deleting it will still drop frames.

**Comment by latenitefilms** [comment]
Just to confirm... are you adding the Metaburner Title AFTER you've deleted all the audio?

**Comment by samplue** [comment]
Yes, I've added and loaded the project data after I've deleted the audio. Just replicated the test again.
It starts to playback fine, but after a couple of seconds it will start dropping frames. This also happens when the media is offline as I've detached the external drive.

**Comment by latenitefilms** [comment]
Curious does it play back ok BEFORE loading a FCPXML? For example, when you see this screen?

<img width="624" alt="image" src="https://github.com/latenitefilms/Metaburner/assets/22286696/eeb66956-2534-4109-8194-5fa475bde911">

**Comment by samplue** [comment]
Yes, it plays back fine without a loaded project.

**Comment by latenitefilms** [comment]
It has something to do with the Motion Template, but I'm not sure what yet.

Creating a new Motion Template with no published parameters works fine.

**Comment by latenitefilms** [comment]
This will be fixed in the next beta.

Apparently FCPX really didn't like me saving MB's of data as a FxPlug Parameter.
